title: The Agent - A Role Playing Game
logo: /assets/img/gamelogo-bck.png
email: marketing@dz9games.com
description: Minimalist is a theme powered by Jekyll. It is modified based on the Minimal theme.
show_downloads: false
google_analytics: UA-108144808-1
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

sidebar:
  - name: Email
    icon: fa-solid fa-envelope
    link: marketing@dz9games.com
  - name: Twitter
    icon: fa-brands fa-twitter
    link: https://twitter.com/dz9_games
  - name: Website
    icon: fa-solid fa-pen
    link: https://theagent.dz9games.com/
